# Generated by Django 6.0.2 on 2026-02-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animalphoto',
            options={'ordering': ['-is_main', 'id'], 'verbose_name': 'Animal Photo', 'verbose_name_plural': 'Animal Photos'},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='microchip_number',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='animalphoto',
            name='created_at',
        ),
        migrations.AddField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='chip_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, help_text='Good, Needs Care, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_available_for_adoption',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='animalphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breed',
            name='characteristics',
            field=models.TextField(blank=True, help_text='Typical traits for this breed'),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.breed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.species'),
        ),
        migrations.AlterField(
            model_name='animalphoto',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='animalphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animalphoto',
            name='image',
            field=models.ImageField(upload_to='animals/'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='animals.species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('name', 'species')},
        ),
    ]
